### ISSUE TITLE
Disable eslint rule `vue/no-multiple-template-root`

### ISSUE THREAD

**Issue by ItsPierre** [jojomatik/nuxt-3-base#166]
**Describe the bug**
Vue 3 supports to have multiple root-elements in the template. This active rule prevents it at the moment.

**To Reproduce**
1. Create a vue-component
2. Add two `div`s in the `template`
3. See error

**Expected behavior**
Since Vue3 supports it, this shouldn't be enabled.

**Comment by jojomatik** [comment]
Thanks for opening the issue @ItsPierre.

As we already discussed I don't think we should disable this rule. Even though vue 3 supports multiple root elements, I would not consider that best practice.

1. A user of a component expects the component tag to be replaced with exactly one element
2. It's not quite transparent to which of the root elements classes and styles are applied

If a component needs multiple elements, they should be nested inside a `div` or similar in my opinion. 

If there are any good reasons for multiple root elements being necessary feel free to comment down below and I will reopen the issue.
