### ISSUE TITLE
Suggestions for the template

### ISSUE THREAD

**Issue by ItsPierre** [jojomatik/nuxt-3-base#172]
**Describe the solution you'd like**

- [x] add an `app.vue` with a `<NuxtPage>` as example
- [x] add a `main.scss` and include it in the `app.vue`
- [x] rename pages `index.vue` to a speaking name. The directories should be used for sub-pages
- [x] add an example `routeRule` for `/` or so in the `nuxt.config.js`
- [x] fix the dark theme in `vuetify.ts`
- [x] add example on how to import images
- [x] add a custom 404-page (error.vue in root)

**Comment by jojomatik** [comment]
Thanks for the suggestions @ItsPierre 

I've gone ahead and implemented nearly all of them.

> * [ ]  add an `app.vue` with a `<NuxtPage>` as example

c255e1fe
> * [ ]  add a `main.scss` and include it in the `app.vue`

dd9a4bf1
> * [ ]  rename pages `index.vue` to a speaking name. The directories should be used for sub-pages

I think this is already the case, there is only one `index.vue` in `/pages/` and I don't believe I can get rid of that? Is there a way @ItsPierre?
> * [ ]  add an example `routeRule` for `/` or so in the `nuxt.config.js`

Not sure what you mean, could you elaborate on this?
> * [ ]  fix the dark theme in `vuetify.ts`

d5ff8e66
> * [ ]  add example on how to import images

8e9acf2b
> * [ ]  add a custom 404-page (error.vue in root)

Does that page get called for every error? If so, how should I decide if it is a 404?

**Comment by ItsPierre** [comment]
> > * [ ]   rename pages `index.vue` to a speaking name. The directories should be used for sub-pages
> 
> I think this is already the case, there is only one `index.vue` in `/pages/` and I don't believe I can get rid of that? Is there a way @ItsPierre?

Yes, if the `app.vue` is added, too, the `index.vue` inside `/pages/` is also correct.

> > * [ ]   add an example `routeRule` for `/` or so in the `nuxt.config.js`
> 
> Not sure what you mean, could you elaborate on this?

Thats deprecated, please ignore. This should be an example on how to redirect to pages, but thats better done in the page itself.

> > * [ ]   add a custom 404-page (error.vue in root)
> 
> Does that page get called for every error? If so, how should I decide if it is a 404?

See [here](https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page).

**Comment by jojomatik** [comment]
> > * [ ]   add a custom 404-page (error.vue in root)
> 
> Does that page get called for every error? If so, how should I decide if it is a 404?

https://github.com/jojomatik/nuxt-3-base/commit/c6e41f699f3ffea902b37567b7442c01e55c635e
