### ISSUE TITLE
Scoped scss is not scoped

### ISSUE THREAD

**Issue by ItsPierre** [jojomatik/nuxt-3-base#173]
**Describe the bug**
SCSS in a scoped `style` tag is not scoped anymore.
In a clean Vue3-project, this still works.

CSS in a scoped `style` tag will apply to the whole application.

**To Reproduce**
1. Add a `scoped` style for a class `test`
2. Add the class `test` in another component to a div
3. See, that this div gets the style

**Expected behavior**
Scoped scss should only apply to the component in which it is defined.

**Comment by jojomatik** [comment]
Hi @ItsPierre, sorry for the late reply. I've tried to reproduce but I don't succeed. 

Please provide an reproduction example, otherwise I will close the issue.

**Comment by ItsPierre** [comment]
I just tested it again and the css is not scoped.

Just create 2 components, use one in the other.

Inner component gets a div with a width and heigth and a class `test`.
Now, add 
```
<style lang="scss" scoped>
.test {
background-color: red;
}
</style>
```
to the outer component and see, that the inner component gets the background color.

**Comment by jojomatik** [comment]
Please fork and push a reproduction example. I'm still not able to reproduce.

**Comment by jojomatik** [comment]
Please fork and push a reproduction example. I'm still not able to reproduce.

**Comment by jojomatik** [comment]
We've just checked. According to the [vue-loader docs](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) a child component's root node is affected by `scoped` styles of the parent component. All other nodes should be unaffected by the `scoped` css. This is the case.

Therefore, this behaviour is by design!
