### ISSUE TITLE
i18n function `$t` shows linting warning when used with more than one parameter

### ISSUE THREAD

**Issue by jojomatik** [jojomatik/nuxt-3-base#5]
**Describe the bug**
Using i18n function `$t` with more than one parameter directly in a template shows linting warning. Using it in the `script` section works properly.

**To Reproduce**
https://github.com/jojomatik/nuxt-3-base/blob/e0729a2dad69d48fb4c7636fa40554ef77ffe625/pages/index.vue#L4-L5

**Expected behavior**
No linting warning is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/66277921/155757504-3cd397aa-6015-480d-9109-4bb7ffdc0b8a.png)

**Environment:**
- WebStorm 2022.1 EAP (Webstorm Build #WS-221.4501.160, built on February 18, 2022)
- Version: 1.0.0-beta.3

**Additional context**
It is currently unclear whether this is an issue with Webstorm, vue-i18n, the linting configuration or if this project missed an essential step of implementing vue-i18n in https://github.com/jojomatik/nuxt-3-base/commit/9e4fd4bae16d40ae665aa26249cfb950d5168e8d.

**Comment by dtoxvanilla1991** [comment]
Hi! 

I am getting exact same error in IDE, although Nuxt 3 runs fine and renders the UI fine with proper translations. Hints?

<img width="739" alt="image" src="https://github.com/jojomatik/nuxt-3-base/assets/73205087/01e61858-61f3-436e-b155-75339b587b1e">
------
<img width="375" alt="image" src="https://github.com/jojomatik/nuxt-3-base/assets/73205087/85f6a35c-f1a9-497f-9244-e766dd6686fb">
-------
<img width="412" alt="image" src="https://github.com/jojomatik/nuxt-3-base/assets/73205087/eef03ff2-ee46-4cf5-bd47-33d8d9b1cf93">

**Comment by jojomatik** [comment]
Hi @dtoxvanilla1991, I've switched to using the `useI18n` API, which doesn't have the same issue.

It is slightly more complicated as you have to create an `i18n` object in every template and then use `i18n.t()`, but the type support is much better. See for example: https://github.com/jojomatik/nuxt-3-base/blob/4005fbc45b2304065080c22ffd70064bd82873ad/pages/login.vue 

This should also support the second argument without problems

**Comment by dtoxvanilla1991** [comment]
> Hi @dtoxvanilla1991, I've switched to using the `useI18n` API, which doesn't have the same issue.
> 
> 
> 
> It is slightly more complicated as you have to create an `i18n` object in every template and then use `i18n.t()`, but the type support is much better. See for example: https://github.com/jojomatik/nuxt-3-base/blob/4005fbc45b2304065080c22ffd70064bd82873ad/pages/login.vue 
> 
> 
> 
> This should also support the second argument without problems

Thank you!!
This is a solid workaround but while me and @DanielRivers are in the dev mode for the next two-three months, maybe & hopefully they will patch this bug..
TS linting issue although exists, it doesn't affect the compilation and everything works just fine(parses) and renders on the UI. 
And it is also all done by the book 📘 from the official docs on i18n.

**Comment by Zhanahmetova** [comment]
Any updates for this issue?

**Comment by jojomatik** [comment]
> Any updates for this issue?

Hi @Zhanahmetova, unfortunately not. I've completely switched to `i18n.t()` (which works perfectly fine for me) instead of the `$t` function and am not actively looking into this issue anymore. If you find any solutions though, I'd be happy to implement them here.
